version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: users-management-db
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_USER:-default_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-users_management}
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST:-localhost}
    ports:
      - ${DB_PORT:-3307}:3307
  mysql-test:
    image: mysql:5.7
    container_name: users-management-db-test
    env_file:
      - .env
    environment:
      MYSQL_USER: ${DB_TEST_USER:-default_user}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_TEST_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_TEST_DATABASE:-users_management_test}
      MYSQL_ROOT_HOST: ${DB_TEST_ROOT_HOST:-localhost}
    ports:
      - ${DB_TEST_PORT:-3308}:3307
